# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v4.0.0
   hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
    - id: end-of-file-fixer
    - id: pretty-format-json
    - id: trailing-whitespace
 - repo: https://github.com/cmake-lint/cmake-lint
   rev: develop
   hooks:
    - id: cmakelint
 - repo: https://gitlab.com/daverona/pre-commit-cpp
   rev: 0.8.0
   hooks:
    - id: clang-format
      args: ["--style=Google"]
    - id: cpplint
